 
spring:
  profiles:
    active:
    - dev
---    
server:
  port: 80  #注册中心 占用7001 端口，冒号后面必须要有空格                 

spring:
  profiles: dev
  application:
    name: app-admin
  server:
  port: 80
feign:
  hystrix:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.50.200:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
---
server:
  port: 80  #注册中心 占用7001 端口，冒号后面必须要有空格                 

spring:
  profiles: test
  application:
    name: app-admin
  server:
  port: 80
feign:
  hystrix:
    enabled: true
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka