 
spring:
  profiles:
    active:
    - dev
---
server:
  port: 7001   #注册中心 占用7001 端口，冒号后面必须要有空格                 

spring:
  profiles: dev
  application:
    name: springcloud-config-eureka-client
   
    
    
    
eureka:
 instance:
    hostname: localhost 
 client:
    register-with-eureka: false  #当前的eureka-server 自己不注册进服务列表中
    service-url: 
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: false   #不通过eureka获取注册信息
    
    
---
server:
  port: 7901   #注册中心 占用7001 端口，冒号后面必须要有空格                 

spring:
  profiles: test
  application:
    name: springcloud-config-eureka-client
    
    
    
eureka:
 instance:
    hostname: localhost 
 client:
    register-with-eureka: false  #当前的eureka-server 自己不注册进服务列表中
    service-url: 
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: false   #不通过eureka获取注册信息
    
    
       