spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001                    

spring:
  profiles: dev
  application:
    name: systemcore-provider
    
eureka:
  client:
    service-url: 
     defaultZone: http://192.168.50.200:7001/eureka

---
server:
  port: 8001                    

spring:
  profiles: test
  application:
    name: systemcore-provider
    
eureka:
  client:
    service-url: 
     defaultZone: http://192.168.50.200:7001/eureka